# errors.py
class AppError(Exception): ...
class ValidationError(AppError): ...
class NotFoundError(AppError): ...
class ConflictError(AppError): ...        # duplicados (placa, etc.)
class IntegrityError(AppError): ...
